# Everything in this section will be available as an environment variable
REPLICATE_API_TOKEN = "r8_EXRCcMkZ0OIbqiyodux14JdxiiNBAIl2uN07o"
PINECONE_API_TOKEN = "f63c23d9-3365-4327-8a32-ee531639ffe6"
ENVIRONMENT_NAME = "gcp-starter"